package main

import (
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"
)

// =============================================================================
// Istio Ingress 호환 + WorkloadEntry 자동 등록 시뮬레이션
//
// 실제 소스 참조:
//   - pilot/pkg/config/kube/ingress/controller.go     → Ingress Controller
//   - pilot/pkg/config/kube/ingress/ingress.go        → SupportedIngresses, RuleCollection
//   - pilot/pkg/config/kube/ingress/virtualservices.go → VirtualService 변환
//   - pilot/pkg/config/kube/ingress/gateways.go       → Gateway 변환
//   - pilot/pkg/autoregistration/controller.go         → AutoRegistration
//   - pilot/pkg/autoregistration/connections.go        → adsConnections
//
// 핵심 알고리즘:
//   1. K8s Ingress → SupportedIngresses 필터 → RuleCollection → VirtualService + Gateway
//   2. VM xDS 연결 → WorkloadEntry 자동 생성 → 연결 해제 시 유예 기간 후 삭제
//   3. ADS 연결 추적: 다중 연결 지원, 모든 연결 해제 시에만 정리
// =============================================================================

// --- Kubernetes Ingress 모델 ---

type IngressControllerMode int

const (
	ModeOFF     IngressControllerMode = iota
	ModeSTRICT
	ModeDEFAULT
)

type MeshConfig struct {
	IngressControllerMode IngressControllerMode
	IngressClass          string
	IngressService        string
	IngressSelector       string
}

type IngressTLS struct {
	Hosts      []string
	SecretName string
}

type IngressPath struct {
	Path     string
	PathType string // "Exact", "Prefix"
	Backend  IngressBackend
}

type IngressBackend struct {
	ServiceName string
	ServicePort int
}

type IngressRule struct {
	Host  string
	Paths []IngressPath
}

type Ingress struct {
	Name             string
	Namespace        string
	IngressClassName *string
	Annotations      map[string]string
	TLS              []IngressTLS
	Rules            []IngressRule
	CreatedAt        time.Time
}

// --- Istio 내부 모델 ---

type Gateway struct {
	Name      string
	Namespace string
	Selector  map[string]string
	Servers   []GatewayServer
}

type GatewayServer struct {
	Port     GatewayPort
	Hosts    []string
	TLSMode  string
	CredName string
}

type GatewayPort struct {
	Number   int
	Protocol string
	Name     string
}

type VirtualService struct {
	Name     string
	Namespace string
	Hosts    []string
	Gateways []string
	Routes   []HTTPRoute
}

type HTTPRoute struct {
	MatchURI    string
	MatchType   string // "exact", "prefix"
	Destination string
	Port        int
	Weight      int
}

// --- Ingress → Gateway + VirtualService 변환 ---

// shouldProcessIngress는 Ingress가 Istio에서 처리해야 하는지 결정한다.
// 실제: pilot/pkg/config/kube/ingress/virtualservices.go의 shouldProcessIngressWithClass
func shouldProcessIngress(mesh MeshConfig, ing Ingress) bool {
	classAnnotation, hasClass := ing.Annotations["kubernetes.io/ingress.class"]
	if hasClass {
		switch mesh.IngressControllerMode {
		case ModeOFF:
			return false
		case ModeSTRICT, ModeDEFAULT:
			return classAnnotation == mesh.IngressClass
		}
	}
	// 어노테이션 없음
	switch mesh.IngressControllerMode {
	case ModeOFF, ModeSTRICT:
		return false
	case ModeDEFAULT:
		return true
	}
	return false
}

// convertToGateway는 Ingress를 Istio Gateway로 변환한다.
// 실제: pilot/pkg/config/kube/ingress/gateways.go의 convertIngressV1alpha3
func convertToGateway(ing Ingress, mesh MeshConfig, domainSuffix string) Gateway {
	gw := Gateway{
		Name:      fmt.Sprintf("%s-istio-autogenerated-k8s-ingress-%s", ing.Name, ing.Namespace),
		Namespace: "istio-system",
		Selector:  getSelector(mesh.IngressSelector, mesh.IngressService),
	}

	for i, tls := range ing.TLS {
		if tls.SecretName == "" {
			continue
		}
		hosts := tls.Hosts
		if len(hosts) == 0 {
			hosts = []string{"*"}
		}
		gw.Servers = append(gw.Servers, GatewayServer{
			Port: GatewayPort{
				Number:   443,
				Protocol: "HTTPS",
				Name:     fmt.Sprintf("https-443-ingress-%s-%s-%d", ing.Name, ing.Namespace, i),
			},
			Hosts:    hosts,
			TLSMode:  "SIMPLE",
			CredName: tls.SecretName,
		})
	}

	gw.Servers = append(gw.Servers, GatewayServer{
		Port: GatewayPort{
			Number:   80,
			Protocol: "HTTP",
			Name:     fmt.Sprintf("http-80-ingress-%s-%s", ing.Name, ing.Namespace),
		},
		Hosts: []string{"*"},
	})

	return gw
}

func getSelector(ingressSelector, ingressService string) map[string]string {
	if ingressSelector != "" {
		return map[string]string{"istio": ingressSelector}
	}
	if ingressService != "" && ingressService != "istio-ingressgateway" {
		return map[string]string{"istio": ingressService}
	}
	return map[string]string{"istio": "ingressgateway"}
}

// IngressRuleEntry는 개별 규칙을 나타낸다.
type IngressRuleEntry struct {
	IngressName string
	Namespace   string
	RuleIndex   int
	CreatedAt   time.Time
	Host        string
	Paths       []IngressPath
}

// buildRuleCollection은 Ingress 규칙을 호스트별로 그룹핑한다.
// 실제: pilot/pkg/config/kube/ingress/ingress.go의 RuleCollection
func buildRuleCollection(ingresses []Ingress) map[string][]IngressRuleEntry {
	hostRules := make(map[string][]IngressRuleEntry)
	for _, ing := range ingresses {
		for idx, rule := range ing.Rules {
			if len(rule.Paths) == 0 {
				continue
			}
			host := rule.Host
			if host == "" {
				host = "*"
			}
			entry := IngressRuleEntry{
				IngressName: ing.Name,
				Namespace:   ing.Namespace,
				RuleIndex:   idx,
				CreatedAt:   ing.CreatedAt,
				Host:        host,
				Paths:       rule.Paths,
			}
			hostRules[host] = append(hostRules[host], entry)
		}
	}

	// 생성 시간순 정렬
	for host := range hostRules {
		rules := hostRules[host]
		sort.SliceStable(rules, func(i, j int) bool {
			return rules[i].CreatedAt.Before(rules[j].CreatedAt)
		})
		hostRules[host] = rules
	}
	return hostRules
}

// convertToVirtualServices는 호스트별 규칙을 VirtualService로 변환한다.
// 실제: pilot/pkg/config/kube/ingress/virtualservices.go의 VirtualServices
func convertToVirtualServices(hostRules map[string][]IngressRuleEntry, domainSuffix string) []VirtualService {
	var result []VirtualService
	for host, rules := range hostRules {
		if len(rules) == 0 {
			continue
		}
		var httpRoutes []HTTPRoute
		for _, rule := range rules {
			for _, path := range rule.Paths {
				route := HTTPRoute{
					MatchURI:    path.Path,
					MatchType:   strings.ToLower(path.PathType),
					Destination: fmt.Sprintf("%s.%s.svc.%s", path.Backend.ServiceName, rule.Namespace, domainSuffix),
					Port:        path.Backend.ServicePort,
					Weight:      100,
				}
				httpRoutes = append(httpRoutes, route)
			}
		}
		// 경로 정렬: 긴 경로 우선, 같은 길이면 Exact > Prefix
		sort.SliceStable(httpRoutes, func(i, j int) bool {
			li, lj := len(httpRoutes[i].MatchURI), len(httpRoutes[j].MatchURI)
			if li == lj {
				return httpRoutes[i].MatchType == "exact" && httpRoutes[j].MatchType != "exact"
			}
			return li > lj
		})

		gwName := fmt.Sprintf("istio-system/%s-istio-autogenerated-k8s-ingress-%s",
			rules[0].IngressName, rules[0].Namespace)

		vs := VirtualService{
			Name:      fmt.Sprintf("%s-%s-istio-autogenerated-k8s-ingress", strings.ReplaceAll(host, ".", "-"), rules[0].IngressName),
			Namespace: rules[0].Namespace,
			Hosts:     []string{host},
			Gateways:  []string{gwName},
			Routes:    httpRoutes,
		}
		result = append(result, vs)
	}
	return result
}

// --- WorkloadEntry 자동 등록 ---

type WorkloadEntry struct {
	Name        string
	Namespace   string
	Address     string
	Labels      map[string]string
	Network     string
	Locality    string
	Annotations map[string]string
}

type WorkloadGroup struct {
	Name      string
	Namespace string
	Labels    map[string]string
	Template  WorkloadEntry
}

// ProxyMeta는 VM 프록시 메타데이터를 나타낸다.
type ProxyMeta struct {
	ID                string
	IPAddress         string
	Namespace         string
	AutoRegisterGroup string
	Network           string
	ServiceAccount    string
}

// Connection은 xDS 연결을 나타낸다.
type Connection struct {
	ID          string
	Proxy       ProxyMeta
	ConnectedAt time.Time
}

// AdsConnections는 프록시별 활성 연결을 추적한다.
// 실제: pilot/pkg/autoregistration/connections.go
type AdsConnections struct {
	mu      sync.Mutex
	byProxy map[string]map[string]*Connection // proxyKey → connID → connection
}

func NewAdsConnections() *AdsConnections {
	return &AdsConnections{
		byProxy: make(map[string]map[string]*Connection),
	}
}

func proxyKey(p ProxyMeta) string {
	return fmt.Sprintf("%s/%s/%s/%s", p.Network, p.IPAddress, p.AutoRegisterGroup, p.Namespace)
}

func (ac *AdsConnections) Connect(conn *Connection) {
	ac.mu.Lock()
	defer ac.mu.Unlock()
	key := proxyKey(conn.Proxy)
	if ac.byProxy[key] == nil {
		ac.byProxy[key] = make(map[string]*Connection)
	}
	ac.byProxy[key][conn.ID] = conn
}

// Disconnect는 연결을 해제하고 남은 연결이 있는지 반환한다.
func (ac *AdsConnections) Disconnect(conn *Connection) bool {
	ac.mu.Lock()
	defer ac.mu.Unlock()
	key := proxyKey(conn.Proxy)
	conns := ac.byProxy[key]
	if conns == nil {
		return false
	}
	delete(conns, conn.ID)
	if len(conns) == 0 {
		delete(ac.byProxy, key)
		return false // 더 이상 연결 없음
	}
	return true // 아직 다른 연결 있음
}

// AutoRegistrationController는 VM 워크로드 자동 등록을 관리한다.
// 실제: pilot/pkg/autoregistration/controller.go
type AutoRegistrationController struct {
	mu             sync.Mutex
	instanceID     string
	workloadEntries map[string]*WorkloadEntry
	workloadGroups  map[string]*WorkloadGroup
	connections     *AdsConnections
	cleanupDelay   time.Duration
}

func NewAutoRegistrationController(instanceID string) *AutoRegistrationController {
	return &AutoRegistrationController{
		instanceID:      instanceID,
		workloadEntries: make(map[string]*WorkloadEntry),
		workloadGroups:  make(map[string]*WorkloadGroup),
		connections:     NewAdsConnections(),
		cleanupDelay:    200 * time.Millisecond,
	}
}

func (arc *AutoRegistrationController) AddWorkloadGroup(wg *WorkloadGroup) {
	arc.mu.Lock()
	defer arc.mu.Unlock()
	key := wg.Namespace + "/" + wg.Name
	arc.workloadGroups[key] = wg
}

// OnConnect는 프록시 연결 시 WorkloadEntry를 생성/갱신한다.
func (arc *AutoRegistrationController) OnConnect(conn *Connection) error {
	arc.mu.Lock()
	defer arc.mu.Unlock()

	proxy := conn.Proxy
	if proxy.AutoRegisterGroup == "" {
		return nil
	}

	entryName := autoRegisteredName(proxy)
	arc.connections.Connect(conn)

	// 기존 WLE 확인
	wleKey := proxy.Namespace + "/" + entryName
	if wle, exists := arc.workloadEntries[wleKey]; exists {
		// 연결 상태 갱신
		wle.Annotations["istio.io/connectedAt"] = conn.ConnectedAt.Format(time.RFC3339Nano)
		wle.Annotations["istio.io/workloadController"] = arc.instanceID
		delete(wle.Annotations, "istio.io/disconnectedAt")
		fmt.Printf("  [AutoReg] WorkloadEntry 갱신: %s (재접속)\n", wleKey)
		return nil
	}

	// WorkloadGroup 조회
	wgKey := proxy.Namespace + "/" + proxy.AutoRegisterGroup
	wg, ok := arc.workloadGroups[wgKey]
	if !ok {
		return fmt.Errorf("WorkloadGroup %s not found", wgKey)
	}

	// WorkloadEntry 생성
	wle := &WorkloadEntry{
		Name:      entryName,
		Namespace: proxy.Namespace,
		Address:   proxy.IPAddress,
		Labels:    mergeLabels(wg.Template.Labels, wg.Labels),
		Network:   proxy.Network,
		Annotations: map[string]string{
			"istio.io/autoRegistrationGroup": wg.Name,
			"istio.io/connectedAt":           conn.ConnectedAt.Format(time.RFC3339Nano),
			"istio.io/workloadController":    arc.instanceID,
		},
	}
	arc.workloadEntries[wleKey] = wle
	fmt.Printf("  [AutoReg] WorkloadEntry 생성: %s (addr=%s, network=%s)\n",
		wleKey, wle.Address, wle.Network)
	return nil
}

// OnDisconnect는 프록시 연결 해제 시 정리를 예약한다.
func (arc *AutoRegistrationController) OnDisconnect(conn *Connection) {
	proxy := conn.Proxy
	if proxy.AutoRegisterGroup == "" {
		return
	}

	// 다른 연결이 남아있는지 확인
	remaining := arc.connections.Disconnect(conn)
	if remaining {
		fmt.Printf("  [AutoReg] 연결 해제 (다른 연결 남아있음, 정리 안 함): %s\n", conn.ID)
		return
	}

	entryName := autoRegisteredName(proxy)
	wleKey := proxy.Namespace + "/" + entryName

	arc.mu.Lock()
	wle, exists := arc.workloadEntries[wleKey]
	if exists {
		wle.Annotations["istio.io/disconnectedAt"] = time.Now().Format(time.RFC3339Nano)
		delete(wle.Annotations, "istio.io/connectedAt")
		fmt.Printf("  [AutoReg] 연결 해제: %s (유예 기간 시작)\n", wleKey)
	}
	arc.mu.Unlock()

	// 유예 기간 후 정리
	go func() {
		time.Sleep(arc.cleanupDelay)
		arc.mu.Lock()
		defer arc.mu.Unlock()
		wle, exists := arc.workloadEntries[wleKey]
		if !exists {
			return
		}
		// 재접속했는지 확인
		if _, connected := wle.Annotations["istio.io/connectedAt"]; connected {
			fmt.Printf("  [AutoReg] 정리 취소 (재접속됨): %s\n", wleKey)
			return
		}
		delete(arc.workloadEntries, wleKey)
		fmt.Printf("  [AutoReg] WorkloadEntry 삭제: %s\n", wleKey)
	}()
}

func autoRegisteredName(proxy ProxyMeta) string {
	name := proxy.AutoRegisterGroup + "-" + strings.ReplaceAll(proxy.IPAddress, ":", "-")
	if proxy.Network != "" {
		name += "-" + proxy.Network
	}
	if len(name) > 253 {
		name = name[len(name)-253:]
	}
	return name
}

func mergeLabels(base, override map[string]string) map[string]string {
	result := make(map[string]string)
	for k, v := range base {
		result[k] = v
	}
	for k, v := range override {
		result[k] = v
	}
	return result
}

// --- 메인 함수 ---

func main() {
	fmt.Println("=== Istio Ingress 호환 + WorkloadEntry 자동 등록 시뮬레이션 ===")
	fmt.Println()

	// 1. Ingress 필터링
	fmt.Println("--- 1단계: Ingress 필터링 (shouldProcessIngress) ---")
	mesh := MeshConfig{
		IngressControllerMode: ModeDEFAULT,
		IngressClass:          "istio",
		IngressService:        "istio-ingressgateway",
	}

	testCases := []struct {
		name   string
		ing    Ingress
		expect bool
	}{
		{"istio 클래스 (STRICT)", Ingress{Annotations: map[string]string{"kubernetes.io/ingress.class": "istio"}}, true},
		{"nginx 클래스", Ingress{Annotations: map[string]string{"kubernetes.io/ingress.class": "nginx"}}, false},
		{"클래스 없음 (DEFAULT)", Ingress{Annotations: map[string]string{}}, true},
	}

	for _, tc := range testCases {
		result := shouldProcessIngress(mesh, tc.ing)
		match := "OK"
		if result != tc.expect {
			match = "FAIL"
		}
		fmt.Printf("  [%s] %s: 처리=%v (기대=%v)\n", match, tc.name, result, tc.expect)
	}

	// STRICT 모드 테스트
	meshStrict := MeshConfig{IngressControllerMode: ModeSTRICT, IngressClass: "istio"}
	fmt.Printf("  [STRICT] 클래스 없음: 처리=%v (기대=false)\n",
		shouldProcessIngress(meshStrict, Ingress{Annotations: map[string]string{}}))

	// 2. Ingress → Gateway 변환
	fmt.Println()
	fmt.Println("--- 2단계: Ingress → Gateway 변환 ---")
	now := time.Now()
	ing := Ingress{
		Name: "my-app", Namespace: "default",
		CreatedAt: now,
		TLS: []IngressTLS{
			{Hosts: []string{"app.example.com"}, SecretName: "app-tls"},
		},
		Rules: []IngressRule{
			{
				Host: "app.example.com",
				Paths: []IngressPath{
					{Path: "/api", PathType: "Prefix", Backend: IngressBackend{ServiceName: "api-svc", ServicePort: 8080}},
					{Path: "/api/v1/users", PathType: "Exact", Backend: IngressBackend{ServiceName: "users-svc", ServicePort: 8080}},
				},
			},
		},
	}

	gw := convertToGateway(ing, mesh, "cluster.local")
	fmt.Printf("  Gateway: %s/%s\n", gw.Namespace, gw.Name)
	fmt.Printf("  Selector: %v\n", gw.Selector)
	for _, srv := range gw.Servers {
		fmt.Printf("    Server: %s %s:%d hosts=%v\n", srv.Port.Protocol, srv.Port.Name, srv.Port.Number, srv.Hosts)
		if srv.TLSMode != "" {
			fmt.Printf("      TLS: mode=%s, cred=%s\n", srv.TLSMode, srv.CredName)
		}
	}

	// 3. Ingress → VirtualService 변환
	fmt.Println()
	fmt.Println("--- 3단계: Ingress → VirtualService 변환 (경로 정렬 포함) ---")
	hostRules := buildRuleCollection([]Ingress{ing})
	vsList := convertToVirtualServices(hostRules, "cluster.local")
	for _, vs := range vsList {
		fmt.Printf("  VirtualService: %s/%s\n", vs.Namespace, vs.Name)
		fmt.Printf("    Hosts: %v\n", vs.Hosts)
		fmt.Printf("    Gateways: %v\n", vs.Gateways)
		for i, route := range vs.Routes {
			fmt.Printf("    Route[%d]: %s(%s) → %s:%d (weight=%d)\n",
				i, route.MatchType, route.MatchURI, route.Destination, route.Port, route.Weight)
		}
	}

	// 4. WorkloadEntry 자동 등록
	fmt.Println()
	fmt.Println("--- 4단계: WorkloadEntry 자동 등록 ---")
	arc := NewAutoRegistrationController("istiod-0")

	arc.AddWorkloadGroup(&WorkloadGroup{
		Name: "my-vm-group", Namespace: "vm-ns",
		Labels: map[string]string{"app": "my-vm-app"},
		Template: WorkloadEntry{
			Labels: map[string]string{"version": "v1"},
		},
	})

	// VM 연결
	conn1 := &Connection{
		ID: "conn-1",
		Proxy: ProxyMeta{
			ID: "vm-proxy-1", IPAddress: "192.168.1.10",
			Namespace: "vm-ns", AutoRegisterGroup: "my-vm-group",
			Network: "vpc-1",
		},
		ConnectedAt: time.Now(),
	}
	arc.OnConnect(conn1)

	conn2 := &Connection{
		ID: "conn-2",
		Proxy: ProxyMeta{
			ID: "vm-proxy-2", IPAddress: "192.168.1.20",
			Namespace: "vm-ns", AutoRegisterGroup: "my-vm-group",
			Network: "vpc-1",
		},
		ConnectedAt: time.Now(),
	}
	arc.OnConnect(conn2)

	// 5. 다중 연결 시나리오
	fmt.Println()
	fmt.Println("--- 5단계: 다중 연결 + 연결 해제 ---")

	// 같은 프록시의 두 번째 연결
	conn1b := &Connection{
		ID: "conn-1b",
		Proxy: ProxyMeta{
			ID: "vm-proxy-1", IPAddress: "192.168.1.10",
			Namespace: "vm-ns", AutoRegisterGroup: "my-vm-group",
			Network: "vpc-1",
		},
		ConnectedAt: time.Now(),
	}
	arc.OnConnect(conn1b)

	// 첫 번째 연결 해제 (다른 연결 남아있으므로 정리 안 함)
	arc.OnDisconnect(conn1)

	// 6. 완전 연결 해제 + 유예 기간
	fmt.Println()
	fmt.Println("--- 6단계: 완전 연결 해제 + 유예 기간 후 삭제 ---")
	arc.OnDisconnect(conn1b) // 모든 연결 해제 → 유예 기간 시작

	time.Sleep(300 * time.Millisecond) // 유예 기간 대기

	// 7. 재접속 시나리오
	fmt.Println()
	fmt.Println("--- 7단계: 유예 기간 내 재접속 ---")
	arc.cleanupDelay = 300 * time.Millisecond

	conn2b := &Connection{
		ID: "conn-2b",
		Proxy: ProxyMeta{
			ID: "vm-proxy-2", IPAddress: "192.168.1.20",
			Namespace: "vm-ns", AutoRegisterGroup: "my-vm-group",
			Network: "vpc-1",
		},
		ConnectedAt: time.Now(),
	}

	// 연결 해제
	arc.OnDisconnect(conn2)
	// 유예 기간 내에 재접속
	time.Sleep(50 * time.Millisecond)
	arc.OnConnect(conn2b)

	time.Sleep(400 * time.Millisecond) // 유예 기간 경과 대기

	// 현재 상태 확인
	fmt.Println()
	fmt.Println("--- 최종 상태 ---")
	arc.mu.Lock()
	fmt.Printf("  등록된 WorkloadEntry 수: %d\n", len(arc.workloadEntries))
	for key, wle := range arc.workloadEntries {
		fmt.Printf("    %s: addr=%s, network=%s, labels=%v\n",
			key, wle.Address, wle.Network, wle.Labels)
	}
	arc.mu.Unlock()

	// 요약
	fmt.Println()
	fmt.Println("=== 요약 ===")
	fmt.Println("  Ingress 호환:")
	fmt.Println("  - shouldProcessIngress: OFF/STRICT/DEFAULT 모드에 따른 필터링")
	fmt.Println("  - Gateway 생성: TLS Server(443) + HTTP Server(80)")
	fmt.Println("  - VirtualService 생성: 호스트별 규칙 그룹핑, Exact > Prefix 정렬")
	fmt.Println()
	fmt.Println("  WorkloadEntry 자동 등록:")
	fmt.Println("  - OnConnect: WorkloadGroup 템플릿으로 WLE 자동 생성")
	fmt.Println("  - 다중 연결 추적: 모든 연결 해제 시에만 정리 시작")
	fmt.Println("  - 유예 기간: cleanupDelay 이내 재접속 시 삭제 취소")
	fmt.Println("  - 어노테이션 기반 상태: connectedAt, disconnectedAt, workloadController")
}
