// poc-18-build-codegen: Cilium 빌드 시스템 및 코드 생성 메커니즘 시뮬레이션
//
// 이 PoC는 Cilium 프로젝트의 빌드 시스템과 자동 코드 생성 파이프라인의
// 핵심 메커니즘을 순수 Go(stdlib only)로 시뮬레이션한다.
//
// 시뮬레이션 항목:
//   1. Protobuf 유사 코드 생성 (메시지 정의 -> Go 구조체 + Marshal/Unmarshal)
//   2. DeepCopy 코드 생성 (구조체 분석 -> DeepCopy 메서드)
//   3. CRD YAML 생성 (Go 구조체 태그 -> OpenAPI 스키마)
//   4. Makefile 타겟 의존성 그래프 (위상 정렬 기반 빌드 순서)
//   5. 증분 빌드 감지 (파일 수정 시간 기반 재빌드 판단)
//
// 사용법:
//   go run main.go

package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"
	"time"
)

// =============================================================================
// 1. Protobuf 유사 코드 생성
// =============================================================================
// Cilium의 api/v1/flow/flow.proto, api/v1/observer/observer.proto를
// protoc로 컴파일하는 과정을 시뮬레이션한다.

// ProtoFieldType은 protobuf 필드 타입을 나타낸다.
type ProtoFieldType int

const (
	ProtoString ProtoFieldType = iota
	ProtoInt32
	ProtoInt64
	ProtoUint32
	ProtoUint64
	ProtoBool
	ProtoBytes
	ProtoTimestamp
	ProtoEnum
	ProtoMessage
	ProtoRepeatedString
	ProtoRepeatedMessage
)

// ProtoField는 protobuf 메시지의 필드를 나타낸다.
type ProtoField struct {
	Name       string
	Type       ProtoFieldType
	TypeName   string // ProtoMessage/ProtoEnum일 때 타입 이름
	FieldNum   int
	Deprecated bool
	Comment    string
}

// ProtoMessageDef는 protobuf 메시지 정의를 나타낸다.
type ProtoMessageDef struct {
	Name    string
	Fields  []ProtoField
	Package string
	Comment string
}

// ProtoEnumDef는 protobuf enum 정의를 나타낸다.
type ProtoEnumDef struct {
	Name   string
	Values []ProtoEnumValue
}

// ProtoEnumValue는 enum의 값을 나타낸다.
type ProtoEnumValue struct {
	Name  string
	Value int
}

// ProtoService는 gRPC 서비스 정의를 나타낸다.
type ProtoService struct {
	Name    string
	Methods []ProtoMethod
}

// ProtoMethod는 gRPC 메서드를 나타낸다.
type ProtoMethod struct {
	Name         string
	InputType    string
	OutputType   string
	ServerStream bool
	ClientStream bool
}

// ProtoFile은 하나의 .proto 파일을 나타낸다.
type ProtoFile struct {
	Package  string
	GoPackage string
	Messages []ProtoMessageDef
	Enums    []ProtoEnumDef
	Services []ProtoService
}

// protoTypeToGoType은 protobuf 타입을 Go 타입으로 변환한다.
func protoTypeToGoType(ft ProtoFieldType, typeName string) string {
	switch ft {
	case ProtoString:
		return "string"
	case ProtoInt32:
		return "int32"
	case ProtoInt64:
		return "int64"
	case ProtoUint32:
		return "uint32"
	case ProtoUint64:
		return "uint64"
	case ProtoBool:
		return "bool"
	case ProtoBytes:
		return "[]byte"
	case ProtoTimestamp:
		return "time.Time"
	case ProtoEnum:
		return typeName
	case ProtoMessage:
		return "*" + typeName
	case ProtoRepeatedString:
		return "[]string"
	case ProtoRepeatedMessage:
		return "[]*" + typeName
	default:
		return "interface{}"
	}
}

// GoStructTemplate은 protobuf 메시지에서 Go 구조체를 생성하는 템플릿이다.
const GoStructTemplate = `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: {{.Package}}/{{toLower .Name}}.proto

package {{.Package}}

{{range .Enums}}
// {{.Name}} represents the protobuf enum {{.Name}}.
type {{.Name}} int32

const (
{{- range .Values}}
	{{$.Name}}_{{.Name}} {{$.Name}} = {{.Value}}
{{- end}}
)
{{end}}

{{range .Messages}}
// {{.Name}} represents the protobuf message {{.Name}}.
{{- if .Comment}}
// {{.Comment}}
{{- end}}
type {{.Name}} struct {
{{- range .Fields}}
{{- if .Deprecated}}
	// Deprecated: {{.Comment}}
{{- else if .Comment}}
	// {{.Comment}}
{{- end}}
	{{goFieldName .Name}} {{goType .Type .TypeName}} ` + "`" + `protobuf:"{{protoWireType .Type}},{{.FieldNum}},opt,name={{.Name}}" json:"{{.Name}},omitempty"` + "`" + `
{{- end}}
}

// Marshal serializes the {{.Name}} to bytes.
func (m *{{.Name}}) Marshal() ([]byte, error) {
	// 시뮬레이션: 실제로는 protobuf 인코딩 사용
	size := 0
{{- range .Fields}}
	_ = m.{{goFieldName .Name}} // field {{.FieldNum}}
	size += {{.FieldNum}} + 1
{{- end}}
	data := make([]byte, size)
	return data, nil
}

// Unmarshal deserializes bytes into {{.Name}}.
func (m *{{.Name}}) Unmarshal(data []byte) error {
	// 시뮬레이션: 실제로는 protobuf 디코딩 사용
	_ = data
	return nil
}

// MarshalJSON implements custom JSON marshaling.
func (m *{{.Name}}) MarshalJSON() ([]byte, error) {
	// 시뮬레이션: protoc-gen-go-json 생성 코드
	return []byte("{}"), nil
}
{{end}}

{{range .Services}}
// {{.Name}}Server is the server API for {{.Name}} service.
type {{.Name}}Server interface {
{{- range .Methods}}
{{- if .ServerStream}}
	{{.Name}}(*{{.InputType}}, {{$.Name}}_{{.Name}}Server) error
{{- else}}
	{{.Name}}(*{{.InputType}}) (*{{.OutputType}}, error)
{{- end}}
{{- end}}
}

// {{.Name}}Client is the client API for {{.Name}} service.
type {{.Name}}Client interface {
{{- range .Methods}}
{{- if .ServerStream}}
	{{.Name}}(*{{.InputType}}) ({{$.Name}}_{{.Name}}Client, error)
{{- else}}
	{{.Name}}(*{{.InputType}}) (*{{.OutputType}}, error)
{{- end}}
{{- end}}
}
{{end}}
`

// generateProtobufCode는 ProtoFile로부터 Go 코드를 생성한다.
func generateProtobufCode(pf *ProtoFile) string {
	funcMap := template.FuncMap{
		"toLower": strings.ToLower,
		"goFieldName": func(name string) string {
			parts := strings.Split(name, "_")
			result := ""
			for _, p := range parts {
				if len(p) > 0 {
					result += strings.ToUpper(p[:1]) + p[1:]
				}
			}
			return result
		},
		"goType": protoTypeToGoType,
		"protoWireType": func(ft ProtoFieldType) string {
			switch ft {
			case ProtoString, ProtoBytes:
				return "bytes"
			case ProtoInt32, ProtoInt64, ProtoUint32, ProtoUint64, ProtoBool, ProtoEnum:
				return "varint"
			default:
				return "bytes"
			}
		},
	}

	tmpl, err := template.New("proto").Funcs(funcMap).Parse(GoStructTemplate)
	if err != nil {
		panic(fmt.Sprintf("template parse error: %v", err))
	}

	data := struct {
		Package  string
		Name     string
		Messages []ProtoMessageDef
		Enums    []ProtoEnumDef
		Services []ProtoService
	}{
		Package:  pf.Package,
		Name:     pf.Package,
		Messages: pf.Messages,
		Enums:    pf.Enums,
		Services: pf.Services,
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		panic(fmt.Sprintf("template execute error: %v", err))
	}
	return buf.String()
}

func demoProtobufCodegen() {
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println("  1. PROTOBUF 코드 생성 시뮬레이션")
	fmt.Println("     (Cilium api/v1/flow/flow.proto -> flow.pb.go)")
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println()

	// Cilium의 Flow 메시지를 간소화하여 정의
	flowProto := &ProtoFile{
		Package:   "flow",
		GoPackage: "github.com/cilium/cilium/api/v1/flow",
		Enums: []ProtoEnumDef{
			{
				Name: "Verdict",
				Values: []ProtoEnumValue{
					{Name: "VERDICT_UNKNOWN", Value: 0},
					{Name: "FORWARDED", Value: 1},
					{Name: "DROPPED", Value: 2},
					{Name: "ERROR", Value: 3},
					{Name: "AUDIT", Value: 4},
					{Name: "REDIRECTED", Value: 5},
					{Name: "TRACED", Value: 6},
					{Name: "TRANSLATED", Value: 7},
				},
			},
			{
				Name: "TrafficDirection",
				Values: []ProtoEnumValue{
					{Name: "TRAFFIC_DIRECTION_UNKNOWN", Value: 0},
					{Name: "INGRESS", Value: 1},
					{Name: "EGRESS", Value: 2},
				},
			},
		},
		Messages: []ProtoMessageDef{
			{
				Name:    "Endpoint",
				Package: "flow",
				Comment: "Endpoint is the representation of a network endpoint",
				Fields: []ProtoField{
					{Name: "id", Type: ProtoUint32, FieldNum: 1, Comment: "Cilium endpoint ID"},
					{Name: "identity", Type: ProtoUint32, FieldNum: 2, Comment: "Security identity"},
					{Name: "namespace", Type: ProtoString, FieldNum: 3},
					{Name: "labels", Type: ProtoRepeatedString, FieldNum: 4, Comment: "Labels in key=value format"},
					{Name: "pod_name", Type: ProtoString, FieldNum: 5},
				},
			},
			{
				Name:    "Flow",
				Package: "flow",
				Comment: "Flow represents a single network flow observed by Hubble",
				Fields: []ProtoField{
					{Name: "time", Type: ProtoTimestamp, FieldNum: 1, Comment: "Timestamp of the flow event"},
					{Name: "uuid", Type: ProtoString, FieldNum: 34},
					{Name: "verdict", Type: ProtoEnum, TypeName: "Verdict", FieldNum: 2},
					{Name: "drop_reason", Type: ProtoUint32, FieldNum: 3, Deprecated: true, Comment: "use drop_reason_desc instead"},
					{Name: "source", Type: ProtoMessage, TypeName: "Endpoint", FieldNum: 8},
					{Name: "destination", Type: ProtoMessage, TypeName: "Endpoint", FieldNum: 9},
					{Name: "node_name", Type: ProtoString, FieldNum: 11, Comment: "Name of the node"},
					{Name: "source_names", Type: ProtoRepeatedString, FieldNum: 13, Comment: "DNS names for source IP"},
					{Name: "traffic_direction", Type: ProtoEnum, TypeName: "TrafficDirection", FieldNum: 22},
					{Name: "is_reply", Type: ProtoBool, FieldNum: 26},
				},
			},
		},
		Services: []ProtoService{
			{
				Name: "Observer",
				Methods: []ProtoMethod{
					{Name: "GetFlows", InputType: "GetFlowsRequest", OutputType: "GetFlowsResponse", ServerStream: true},
					{Name: "GetNodes", InputType: "GetNodesRequest", OutputType: "GetNodesResponse"},
					{Name: "ServerStatus", InputType: "ServerStatusRequest", OutputType: "ServerStatusResponse"},
				},
			},
		},
	}

	fmt.Println("입력 (Proto 정의):")
	fmt.Println("  Package: flow")
	fmt.Println("  Enums: Verdict (8 values), TrafficDirection (3 values)")
	fmt.Println("  Messages: Endpoint (5 fields), Flow (10 fields)")
	fmt.Println("  Services: Observer (3 methods, GetFlows=server-stream)")
	fmt.Println()

	code := generateProtobufCode(flowProto)

	fmt.Println("생성된 코드 (flow.pb.go):")
	fmt.Println(strings.Repeat("-", 60))
	// 출력을 제한하여 핵심 부분만 표시
	lines := strings.Split(code, "\n")
	maxLines := 80
	if len(lines) > maxLines {
		for _, line := range lines[:maxLines] {
			fmt.Println(line)
		}
		fmt.Printf("... (%d 줄 더)\n", len(lines)-maxLines)
	} else {
		fmt.Print(code)
	}
	fmt.Println(strings.Repeat("-", 60))
	fmt.Printf("총 %d 줄 생성됨\n\n", len(lines))
}

// =============================================================================
// 2. DeepCopy 코드 생성 시뮬레이션
// =============================================================================
// Cilium의 pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go 생성을
// 시뮬레이션한다.

// FieldKind는 구조체 필드의 종류를 나타낸다.
type FieldKind int

const (
	FieldPrimitive FieldKind = iota // int, string, bool 등
	FieldPointer                    // *T
	FieldSlice                      // []T
	FieldMap                        // map[K]V
	FieldStruct                     // 중첩 구조체
)

// StructField는 구조체의 필드 정보를 나타낸다.
type StructField struct {
	Name     string
	TypeName string
	Kind     FieldKind
	ElemType string // 슬라이스/맵의 원소 타입
	KeyType  string // 맵의 키 타입
}

// StructDef는 구조체 정의를 나타낸다.
type StructDef struct {
	Name        string
	Fields      []StructField
	Markers     []string // +k8s:deepcopy-gen 마커
	IsRuntimeObj bool    // runtime.Object 인터페이스 구현 여부
}

// DeepCopyTemplate은 DeepCopy 코드를 생성하는 템플릿이다.
const DeepCopyTemplate = `//go:build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package {{.PackageName}}

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

{{range .Structs}}
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *{{.Name}}) DeepCopyInto(out *{{.Name}}) {
	*out = *in
{{- range .Fields}}
{{- if eq .Kind 1}} {{/* FieldPointer */}}
	if in.{{.Name}} != nil {
		in, out := &in.{{.Name}}, &out.{{.Name}}
		*out = new({{.ElemType}})
		{{- if eq .ElemType "string"}}
		**out = **in
		{{- else}}
		(*in).DeepCopyInto(*out)
		{{- end}}
	}
{{- else if eq .Kind 2}} {{/* FieldSlice */}}
	if in.{{.Name}} != nil {
		in, out := &in.{{.Name}}, &out.{{.Name}}
		*out = make([]{{.ElemType}}, len(*in))
		{{- if eq .ElemType "string"}}
		copy(*out, *in)
		{{- else}}
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		{{- end}}
	}
{{- else if eq .Kind 3}} {{/* FieldMap */}}
	if in.{{.Name}} != nil {
		in, out := &in.{{.Name}}, &out.{{.Name}}
		*out = make(map[{{.KeyType}}]{{.ElemType}}, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
{{- else if eq .Kind 4}} {{/* FieldStruct */}}
	in.{{.Name}}.DeepCopyInto(&out.{{.Name}})
{{- end}}
{{- end}}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new {{.Name}}.
func (in *{{.Name}}) DeepCopy() *{{.Name}} {
	if in == nil {
		return nil
	}
	out := new({{.Name}})
	in.DeepCopyInto(out)
	return out
}
{{if .IsRuntimeObj}}
// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *{{.Name}}) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
{{end}}
{{end}}
`

// generateDeepCopyCode는 구조체 정의로부터 DeepCopy 코드를 생성한다.
func generateDeepCopyCode(packageName string, structs []StructDef) string {
	tmpl, err := template.New("deepcopy").Parse(DeepCopyTemplate)
	if err != nil {
		panic(fmt.Sprintf("template parse error: %v", err))
	}

	data := struct {
		PackageName string
		Structs     []StructDef
	}{
		PackageName: packageName,
		Structs:     structs,
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		panic(fmt.Sprintf("template execute error: %v", err))
	}
	return buf.String()
}

func demoDeepCopyCodegen() {
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println("  2. DEEPCOPY 코드 생성 시뮬레이션")
	fmt.Println("     (Cilium pkg/k8s/apis/cilium.io/v2/ -> zz_generated.deepcopy.go)")
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println()

	// Cilium CRD 타입을 간소화하여 정의
	structs := []StructDef{
		{
			Name: "CiliumNetworkPolicySpec",
			Fields: []StructField{
				{Name: "Description", TypeName: "string", Kind: FieldPrimitive},
				{Name: "EndpointSelector", TypeName: "EndpointSelector", Kind: FieldStruct},
				{Name: "Ingress", TypeName: "IngressRule", Kind: FieldSlice, ElemType: "IngressRule"},
				{Name: "Egress", TypeName: "EgressRule", Kind: FieldSlice, ElemType: "EgressRule"},
				{Name: "Labels", TypeName: "map[string]string", Kind: FieldMap, KeyType: "string", ElemType: "string"},
			},
			Markers:      []string{"+k8s:deepcopy-gen=true"},
			IsRuntimeObj: false,
		},
		{
			Name: "CiliumNetworkPolicy",
			Fields: []StructField{
				{Name: "TypeMeta", TypeName: "metav1.TypeMeta", Kind: FieldPrimitive},
				{Name: "ObjectMeta", TypeName: "metav1.ObjectMeta", Kind: FieldStruct},
				{Name: "Spec", TypeName: "CiliumNetworkPolicySpec", Kind: FieldPointer, ElemType: "CiliumNetworkPolicySpec"},
				{Name: "Specs", TypeName: "[]CiliumNetworkPolicySpec", Kind: FieldSlice, ElemType: "CiliumNetworkPolicySpec"},
				{Name: "Status", TypeName: "Status", Kind: FieldStruct},
			},
			Markers:      []string{"+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object"},
			IsRuntimeObj: true,
		},
		{
			Name: "CiliumNode",
			Fields: []StructField{
				{Name: "TypeMeta", TypeName: "metav1.TypeMeta", Kind: FieldPrimitive},
				{Name: "ObjectMeta", TypeName: "metav1.ObjectMeta", Kind: FieldStruct},
				{Name: "Spec", TypeName: "NodeSpec", Kind: FieldStruct},
				{Name: "Status", TypeName: "NodeStatus", Kind: FieldStruct},
			},
			Markers:      []string{"+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object"},
			IsRuntimeObj: true,
		},
	}

	fmt.Println("입력 (Go 구조체 분석 결과):")
	for _, s := range structs {
		fmt.Printf("  struct %s (%d fields, markers: %v)\n", s.Name, len(s.Fields), s.Markers)
		for _, f := range s.Fields {
			kindStr := map[FieldKind]string{
				FieldPrimitive: "primitive",
				FieldPointer:   "pointer",
				FieldSlice:     "slice",
				FieldMap:       "map",
				FieldStruct:    "struct",
			}[f.Kind]
			fmt.Printf("    - %s: %s (%s)\n", f.Name, f.TypeName, kindStr)
		}
	}
	fmt.Println()

	code := generateDeepCopyCode("v2", structs)

	fmt.Println("생성된 코드 (zz_generated.deepcopy.go):")
	fmt.Println(strings.Repeat("-", 60))
	lines := strings.Split(code, "\n")
	maxLines := 70
	if len(lines) > maxLines {
		for _, line := range lines[:maxLines] {
			fmt.Println(line)
		}
		fmt.Printf("... (%d 줄 더)\n", len(lines)-maxLines)
	} else {
		fmt.Print(code)
	}
	fmt.Println(strings.Repeat("-", 60))
	fmt.Printf("총 %d 줄 생성됨\n\n", len(lines))
}

// =============================================================================
// 3. CRD YAML 생성 시뮬레이션
// =============================================================================
// Cilium의 controller-gen이 Go 구조체로부터 CRD YAML을 생성하는 과정을
// 시뮬레이션한다.

// CRDField는 CRD 스키마에 들어갈 필드 정보를 나타낸다.
type CRDField struct {
	Name        string
	Type        string // string, integer, boolean, object, array
	Description string
	Required    bool
	Format      string // cidr, date-time 등
	Items       *CRDField // array일 때 원소 스키마
	Properties  []CRDField // object일 때 하위 필드
}

// CRDSpec은 CRD 생성에 필요한 정보를 나타낸다.
type CRDSpec struct {
	Group        string
	Version      string
	Kind         string
	Plural       string
	Singular     string
	ShortNames   []string
	Scope        string // Namespaced, Cluster
	Categories   []string
	PrintColumns []CRDPrintColumn
	Fields       []CRDField
}

// CRDPrintColumn은 kubectl get 출력에 표시할 열을 나타낸다.
type CRDPrintColumn struct {
	Name        string
	Type        string
	JSONPath    string
	Description string
	Priority    int
}

// CRDYAMLTemplate은 CRD YAML을 생성하는 템플릿이다.
const CRDYAMLTemplate = `---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: {{.Plural}}.{{.Group}}
spec:
  group: {{.Group}}
  names:
    kind: {{.Kind}}
    listKind: {{.Kind}}List
    plural: {{.Plural}}
    singular: {{.Singular}}
{{- if .ShortNames}}
    shortNames:
{{- range .ShortNames}}
    - {{.}}
{{- end}}
{{- end}}
{{- if .Categories}}
    categories:
{{- range .Categories}}
    - {{.}}
{{- end}}
{{- end}}
  scope: {{.Scope}}
  versions:
  - name: {{.Version}}
    served: true
    storage: true
{{- if .PrintColumns}}
    additionalPrinterColumns:
{{- range .PrintColumns}}
    - name: {{.Name}}
      type: {{.Type}}
      jsonPath: {{.JSONPath}}
      description: "{{.Description}}"
{{- if gt .Priority 0}}
      priority: {{.Priority}}
{{- end}}
{{- end}}
{{- end}}
    schema:
      openAPIV3Schema:
        description: {{.Kind}} is the Cilium custom resource definition.
        type: object
        required:
        - metadata
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: Spec is the desired state of the {{.Kind}}.
            type: object
            properties:
{{- range .Fields}}
              {{.Name}}:
                description: "{{.Description}}"
                type: {{.Type}}
{{- if .Format}}
                format: {{.Format}}
{{- end}}
{{- if eq .Type "array"}}
{{- if .Items}}
                items:
                  type: {{.Items.Type}}
{{- if .Items.Properties}}
                  properties:
{{- range .Items.Properties}}
                    {{.Name}}:
                      description: "{{.Description}}"
                      type: {{.Type}}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
{{- if and (eq .Type "object") .Properties}}
                properties:
{{- range .Properties}}
                  {{.Name}}:
                    description: "{{.Description}}"
                    type: {{.Type}}
{{- end}}
{{- end}}
{{- end}}
          status:
            description: Status is the most recent observed status of the {{.Kind}}.
            type: object
            x-kubernetes-preserve-unknown-fields: true
`

// generateCRDYAML은 CRDSpec으로부터 CRD YAML을 생성한다.
func generateCRDYAML(spec *CRDSpec) string {
	tmpl, err := template.New("crd").Parse(CRDYAMLTemplate)
	if err != nil {
		panic(fmt.Sprintf("template parse error: %v", err))
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, spec); err != nil {
		panic(fmt.Sprintf("template execute error: %v", err))
	}
	return buf.String()
}

func demoCRDCodegen() {
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println("  3. CRD YAML 생성 시뮬레이션")
	fmt.Println("     (Cilium pkg/k8s/apis/cilium.io/v2/types.go -> CRD YAML)")
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println()

	// CiliumNetworkPolicy CRD를 시뮬레이션
	cnpCRD := &CRDSpec{
		Group:    "cilium.io",
		Version:  "v2",
		Kind:     "CiliumNetworkPolicy",
		Plural:   "ciliumnetworkpolicies",
		Singular: "ciliumnetworkpolicy",
		ShortNames: []string{"cnp", "ciliumnp"},
		Scope:    "Namespaced",
		Categories: []string{"cilium"},
		PrintColumns: []CRDPrintColumn{
			{Name: "Age", Type: "date", JSONPath: ".metadata.creationTimestamp"},
		},
		Fields: []CRDField{
			{
				Name:        "description",
				Type:        "string",
				Description: "Description is a free form string to describe the policy rule.",
			},
			{
				Name:        "endpointSelector",
				Type:        "object",
				Description: "EndpointSelector selects all endpoints which should be subject to this rule.",
				Properties: []CRDField{
					{Name: "matchLabels", Type: "object", Description: "Map of string keys and values for matching."},
				},
			},
			{
				Name:        "ingress",
				Type:        "array",
				Description: "List of rules to be applied to ingress traffic.",
				Items: &CRDField{
					Type: "object",
					Properties: []CRDField{
						{Name: "fromEndpoints", Type: "array", Description: "List of endpoints that are allowed to communicate."},
						{Name: "toPorts", Type: "array", Description: "List of L4 port/protocol pairs."},
					},
				},
			},
			{
				Name:        "egress",
				Type:        "array",
				Description: "List of rules to be applied to egress traffic.",
				Items: &CRDField{
					Type: "object",
					Properties: []CRDField{
						{Name: "toEndpoints", Type: "array", Description: "List of endpoints that are allowed as destinations."},
						{Name: "toPorts", Type: "array", Description: "List of L4 port/protocol pairs."},
						{Name: "toCIDR", Type: "array", Description: "List of CIDRs allowed as destination."},
					},
				},
			},
		},
	}

	fmt.Println("입력 (Go 구조체 kubebuilder 마커 분석):")
	fmt.Printf("  Kind: %s\n", cnpCRD.Kind)
	fmt.Printf("  Group: %s, Version: %s\n", cnpCRD.Group, cnpCRD.Version)
	fmt.Printf("  Scope: %s\n", cnpCRD.Scope)
	fmt.Printf("  Short Names: %v\n", cnpCRD.ShortNames)
	fmt.Printf("  Fields: %d top-level properties\n", len(cnpCRD.Fields))
	fmt.Println()

	yaml := generateCRDYAML(cnpCRD)

	fmt.Println("생성된 CRD (ciliumnetworkpolicies.yaml):")
	fmt.Println(strings.Repeat("-", 60))
	lines := strings.Split(yaml, "\n")
	maxLines := 60
	if len(lines) > maxLines {
		for _, line := range lines[:maxLines] {
			fmt.Println(line)
		}
		fmt.Printf("... (%d 줄 더)\n", len(lines)-maxLines)
	} else {
		fmt.Print(yaml)
	}
	fmt.Println(strings.Repeat("-", 60))
	fmt.Printf("총 %d 줄 YAML 생성됨\n\n", len(lines))
}

// =============================================================================
// 4. Makefile 타겟 의존성 그래프 시뮬레이션
// =============================================================================
// Cilium의 Makefile 빌드 타겟 의존성을 위상 정렬하여 빌드 순서를 결정한다.

// BuildTarget은 Makefile의 빌드 타겟을 나타낸다.
type BuildTarget struct {
	Name         string
	Dependencies []string
	Description  string
	Commands     []string
	Phony        bool
}

// BuildGraph는 빌드 의존성 그래프를 나타낸다.
type BuildGraph struct {
	Targets map[string]*BuildTarget
}

// NewBuildGraph는 새 빌드 그래프를 생성한다.
func NewBuildGraph() *BuildGraph {
	return &BuildGraph{
		Targets: make(map[string]*BuildTarget),
	}
}

// AddTarget은 빌드 타겟을 추가한다.
func (g *BuildGraph) AddTarget(t *BuildTarget) {
	g.Targets[t.Name] = t
}

// TopologicalSort는 위상 정렬하여 빌드 순서를 반환한다.
func (g *BuildGraph) TopologicalSort() ([]string, error) {
	visited := make(map[string]bool)
	visiting := make(map[string]bool)
	var order []string

	var visit func(name string) error
	visit = func(name string) error {
		if visited[name] {
			return nil
		}
		if visiting[name] {
			return fmt.Errorf("cycle detected at target: %s", name)
		}

		visiting[name] = true

		if target, ok := g.Targets[name]; ok {
			for _, dep := range target.Dependencies {
				if err := visit(dep); err != nil {
					return err
				}
			}
		}

		visiting[name] = false
		visited[name] = true
		order = append(order, name)
		return nil
	}

	// 모든 타겟에 대해 방문
	names := make([]string, 0, len(g.Targets))
	for name := range g.Targets {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		if err := visit(name); err != nil {
			return nil, err
		}
	}

	return order, nil
}

// ResolveBuild는 특정 타겟을 빌드하기 위해 필요한 타겟 목록을 순서대로 반환한다.
func (g *BuildGraph) ResolveBuild(target string) ([]string, error) {
	visited := make(map[string]bool)
	var order []string

	var visit func(name string) error
	visit = func(name string) error {
		if visited[name] {
			return nil
		}
		visited[name] = true

		if t, ok := g.Targets[name]; ok {
			for _, dep := range t.Dependencies {
				if err := visit(dep); err != nil {
					return err
				}
			}
		}

		order = append(order, name)
		return nil
	}

	if err := visit(target); err != nil {
		return nil, err
	}
	return order, nil
}

// PrintDependencyTree는 의존성 트리를 시각화한다.
func (g *BuildGraph) PrintDependencyTree(target string, indent int, visited map[string]bool) {
	if visited == nil {
		visited = make(map[string]bool)
	}
	prefix := strings.Repeat("  ", indent)

	t, ok := g.Targets[target]
	if !ok {
		fmt.Printf("%s%s (external)\n", prefix, target)
		return
	}

	marker := ""
	if visited[target] {
		fmt.Printf("%s%s (already shown)\n", prefix, target)
		return
	}
	visited[target] = true

	if t.Phony {
		marker = " [PHONY]"
	}
	fmt.Printf("%s%s%s - %s\n", prefix, target, marker, t.Description)

	for _, dep := range t.Dependencies {
		g.PrintDependencyTree(dep, indent+1, visited)
	}
}

func demoBuildGraph() {
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println("  4. MAKEFILE 빌드 의존성 그래프 시뮬레이션")
	fmt.Println("     (Cilium Makefile 타겟 의존성 분석)")
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println()

	graph := NewBuildGraph()

	// Cilium의 실제 Makefile 타겟들을 시뮬레이션
	graph.AddTarget(&BuildTarget{
		Name: "all", Dependencies: []string{"precheck", "build", "postcheck"},
		Description: "기본 타겟: precheck -> build -> postcheck", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "precheck", Dependencies: []string{"check-fmt", "check-log", "check-viper", "custom-vet", "check-fuzz"},
		Description: "빌드 전 코드 품질 검사", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "check-fmt", Description: "Go 포맷 검사 (gofmt)", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "check-log", Description: "로그 메시지 형식 검사", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "check-viper", Description: "Viper 설정 사용 검사", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "custom-vet", Description: "커스텀 vet 검사", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "check-fuzz", Description: "퍼저 검사", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "build", Dependencies: []string{"daemon", "operator", "hubble-relay", "bpf", "plugins", "cilium-dbg"},
		Description: "전체 바이너리 빌드", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "daemon", Dependencies: []string{"GIT_VERSION"},
		Description: "cilium-agent 바이너리", Phony: true,
		Commands: []string{"go build -o cilium-agent ./daemon"},
	})
	graph.AddTarget(&BuildTarget{
		Name: "operator", Dependencies: []string{"GIT_VERSION"},
		Description: "cilium-operator 바이너리", Phony: true,
		Commands: []string{"go build -o cilium-operator-generic ./operator"},
	})
	graph.AddTarget(&BuildTarget{
		Name: "hubble-relay", Dependencies: []string{"GIT_VERSION"},
		Description: "hubble-relay 바이너리", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "cilium-dbg", Dependencies: []string{"GIT_VERSION"},
		Description: "cilium-dbg CLI 바이너리", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "plugins", Dependencies: []string{"GIT_VERSION"},
		Description: "CNI 플러그인 등", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "bpf", Dependencies: []string{"bpf_lxc.o", "bpf_host.o", "bpf_overlay.o", "bpf_xdp.o", "bpf_sock.o"},
		Description: "BPF 프로그램 컴파일", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "bpf_lxc.o", Dependencies: []string{"bpf_lxc.c", "bpf_headers"},
		Description: "컨테이너 네트워킹 BPF",
		Commands: []string{"clang --target=bpf -O2 -c bpf_lxc.c -o bpf_lxc.o"},
	})
	graph.AddTarget(&BuildTarget{
		Name: "bpf_host.o", Dependencies: []string{"bpf_host.c", "bpf_headers"},
		Description: "호스트 네트워킹 BPF",
	})
	graph.AddTarget(&BuildTarget{
		Name: "bpf_overlay.o", Dependencies: []string{"bpf_overlay.c", "bpf_headers"},
		Description: "오버레이 네트워킹 BPF",
	})
	graph.AddTarget(&BuildTarget{
		Name: "bpf_xdp.o", Dependencies: []string{"bpf_xdp.c", "bpf_headers"},
		Description: "XDP 가속 BPF",
	})
	graph.AddTarget(&BuildTarget{
		Name: "bpf_sock.o", Dependencies: []string{"bpf_sock.c", "bpf_headers"},
		Description: "소켓 LB BPF",
	})
	graph.AddTarget(&BuildTarget{
		Name: "bpf_headers", Description: "BPF 헤더 파일들 (*.h)", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "GIT_VERSION", Description: "Git 버전 정보 파일",
	})
	graph.AddTarget(&BuildTarget{
		Name: "postcheck", Dependencies: []string{"build"},
		Description: "빌드 후 검증 (문서, 명령어 참조 등)", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "generate-apis", Dependencies: []string{"generate-api", "generate-hubble-api", "generate-health-api", "generate-operator-api"},
		Description: "전체 API 코드 생성", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "generate-api", Dependencies: []string{"openapi.yaml"},
		Description: "Swagger REST API 코드 생성", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "generate-hubble-api", Dependencies: []string{"flow.proto", "observer.proto"},
		Description: "Protobuf gRPC API 코드 생성", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "generate-health-api", Dependencies: []string{"health-openapi.yaml"},
		Description: "Health API 코드 생성", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "generate-operator-api", Dependencies: []string{"operator-openapi.yaml"},
		Description: "Operator API 코드 생성", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "manifests", Dependencies: []string{"controller-gen"},
		Description: "CRD YAML 매니페스트 생성", Phony: true,
	})
	graph.AddTarget(&BuildTarget{
		Name: "docker-cilium-image", Dependencies: []string{"GIT_VERSION", "Dockerfile"},
		Description: "cilium-agent Docker 이미지 빌드", Phony: true,
	})

	// 의존성 트리 출력
	fmt.Println("[의존성 트리: 'all' 타겟]")
	fmt.Println()
	graph.PrintDependencyTree("all", 0, nil)

	fmt.Println()
	fmt.Println("[의존성 트리: 'generate-apis' 타겟]")
	fmt.Println()
	graph.PrintDependencyTree("generate-apis", 0, nil)

	// 빌드 순서 해결
	fmt.Println()
	fmt.Println("[빌드 순서 해결: 'all' 타겟]")
	order, err := graph.ResolveBuild("all")
	if err != nil {
		fmt.Printf("  ERROR: %v\n", err)
	} else {
		for i, name := range order {
			t := graph.Targets[name]
			desc := "(external)"
			if t != nil {
				desc = t.Description
			}
			fmt.Printf("  Step %2d: %-20s  # %s\n", i+1, name, desc)
		}
	}

	// 전체 위상 정렬
	fmt.Println()
	fmt.Println("[전체 빌드 그래프 위상 정렬]")
	fullOrder, err := graph.TopologicalSort()
	if err != nil {
		fmt.Printf("  ERROR: %v\n", err)
	} else {
		fmt.Printf("  %d 타겟, 정렬된 빌드 순서:\n", len(fullOrder))
		for i, name := range fullOrder {
			fmt.Printf("  %2d. %s\n", i+1, name)
		}
	}
	fmt.Println()
}

// =============================================================================
// 5. 증분 빌드 감지 시뮬레이션
// =============================================================================
// Makefile의 파일 수정 시간 기반 재빌드 판단 로직을 시뮬레이션한다.

// FileInfo는 빌드 파일의 정보를 나타낸다.
type FileInfo struct {
	Path     string
	ModTime  time.Time
	IsTarget bool // 빌드 산출물인지 여부
}

// IncrementalBuildChecker는 증분 빌드 필요 여부를 판단한다.
type IncrementalBuildChecker struct {
	Files map[string]*FileInfo
	Rules map[string][]string // target -> dependencies
}

// NewIncrementalBuildChecker는 새 증분 빌드 체커를 생성한다.
func NewIncrementalBuildChecker() *IncrementalBuildChecker {
	return &IncrementalBuildChecker{
		Files: make(map[string]*FileInfo),
		Rules: make(map[string][]string),
	}
}

// AddFile은 파일 정보를 등록한다.
func (c *IncrementalBuildChecker) AddFile(path string, modTime time.Time, isTarget bool) {
	c.Files[path] = &FileInfo{Path: path, ModTime: modTime, IsTarget: isTarget}
}

// AddRule은 빌드 규칙을 등록한다.
func (c *IncrementalBuildChecker) AddRule(target string, deps []string) {
	c.Rules[target] = deps
}

// NeedsRebuild는 대상 파일이 재빌드가 필요한지 판단한다.
func (c *IncrementalBuildChecker) NeedsRebuild(target string) (bool, string) {
	targetFile, ok := c.Files[target]
	if !ok {
		return true, "target does not exist"
	}

	deps, ok := c.Rules[target]
	if !ok {
		return false, "no dependencies defined"
	}

	for _, dep := range deps {
		depFile, ok := c.Files[dep]
		if !ok {
			return true, fmt.Sprintf("dependency '%s' not found", dep)
		}
		if depFile.ModTime.After(targetFile.ModTime) {
			return true, fmt.Sprintf("dependency '%s' is newer (%s > %s)",
				dep,
				depFile.ModTime.Format("15:04:05"),
				targetFile.ModTime.Format("15:04:05"),
			)
		}
	}

	return false, "all dependencies are older than target"
}

// CheckAll은 모든 타겟에 대해 재빌드 필요 여부를 확인한다.
func (c *IncrementalBuildChecker) CheckAll() map[string]bool {
	result := make(map[string]bool)
	for target := range c.Rules {
		needs, _ := c.NeedsRebuild(target)
		result[target] = needs
	}
	return result
}

func demoIncrementalBuild() {
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println("  5. 증분 빌드 감지 시뮬레이션")
	fmt.Println("     (Makefile의 파일 수정 시간 기반 재빌드 판단)")
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println()

	checker := NewIncrementalBuildChecker()

	// 시간 기준점
	now := time.Now()
	hourAgo := now.Add(-1 * time.Hour)
	twoHoursAgo := now.Add(-2 * time.Hour)
	fiveMinAgo := now.Add(-5 * time.Minute)

	// 시나리오: BPF 프로그램 빌드
	fmt.Println("[시나리오 1: BPF 프로그램 빌드]")
	fmt.Println()

	// 소스 파일 (일부는 최근 수정됨)
	checker.AddFile("bpf/bpf_lxc.c", fiveMinAgo, false)      // 최근 수정!
	checker.AddFile("bpf/bpf_host.c", twoHoursAgo, false)     // 오래된 소스
	checker.AddFile("bpf/bpf_overlay.c", twoHoursAgo, false)  // 오래된 소스
	checker.AddFile("bpf/include/bpf/helpers.h", fiveMinAgo, false) // 헤더 수정!
	checker.AddFile("bpf/include/bpf/types.h", twoHoursAgo, false)
	checker.AddFile("bpf/lib/common.h", twoHoursAgo, false)

	// 빌드 산출물 (1시간 전 빌드)
	checker.AddFile("bpf/bpf_lxc.o", hourAgo, true)
	checker.AddFile("bpf/bpf_host.o", hourAgo, true)
	checker.AddFile("bpf/bpf_overlay.o", hourAgo, true)

	// 빌드 규칙
	bpfHeaders := []string{"bpf/include/bpf/helpers.h", "bpf/include/bpf/types.h", "bpf/lib/common.h"}
	checker.AddRule("bpf/bpf_lxc.o", append([]string{"bpf/bpf_lxc.c"}, bpfHeaders...))
	checker.AddRule("bpf/bpf_host.o", append([]string{"bpf/bpf_host.c"}, bpfHeaders...))
	checker.AddRule("bpf/bpf_overlay.o", append([]string{"bpf/bpf_overlay.c"}, bpfHeaders...))

	fmt.Println("  파일 수정 시간:")
	// 파일 목록을 정렬하여 출력
	var paths []string
	for p := range checker.Files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		f := checker.Files[p]
		role := "SRC"
		if f.IsTarget {
			role = "OBJ"
		}
		age := now.Sub(f.ModTime).Round(time.Second)
		fmt.Printf("    [%s] %-40s  %s (-%v)\n", role, p, f.ModTime.Format("15:04:05"), age)
	}
	fmt.Println()

	fmt.Println("  재빌드 판단 결과:")
	for _, target := range []string{"bpf/bpf_lxc.o", "bpf/bpf_host.o", "bpf/bpf_overlay.o"} {
		needs, reason := checker.NeedsRebuild(target)
		status := "SKIP (up-to-date)"
		if needs {
			status = "REBUILD NEEDED"
		}
		fmt.Printf("    %-25s  -> %-20s  # %s\n", target, status, reason)
	}

	// 시나리오 2: Go 바이너리 빌드
	fmt.Println()
	fmt.Println("[시나리오 2: Go 바이너리 빌드]")
	fmt.Println()

	checker2 := NewIncrementalBuildChecker()

	// Go 소스 파일
	checker2.AddFile("daemon/cmd/daemon.go", fiveMinAgo, false)     // 최근 수정
	checker2.AddFile("daemon/cmd/endpoint.go", twoHoursAgo, false)
	checker2.AddFile("pkg/endpoint/endpoint.go", twoHoursAgo, false)
	checker2.AddFile("pkg/policy/policy.go", twoHoursAgo, false)

	// 생성된 코드
	checker2.AddFile("api/v1/models/endpoint.go", twoHoursAgo, false)
	checker2.AddFile("api/v1/flow/flow.pb.go", twoHoursAgo, false)
	checker2.AddFile("pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go", twoHoursAgo, false)

	// 소스 정의 파일
	checker2.AddFile("api/v1/openapi.yaml", fiveMinAgo, false) // 최근 수정!
	checker2.AddFile("api/v1/flow/flow.proto", twoHoursAgo, false)
	checker2.AddFile("pkg/k8s/apis/cilium.io/v2/types.go", twoHoursAgo, false)

	// 바이너리
	checker2.AddFile("daemon/cilium-agent", hourAgo, true)

	// 생성 코드 의존성
	checker2.AddRule("api/v1/models/endpoint.go", []string{"api/v1/openapi.yaml"})
	checker2.AddRule("api/v1/flow/flow.pb.go", []string{"api/v1/flow/flow.proto"})
	checker2.AddRule("pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go", []string{"pkg/k8s/apis/cilium.io/v2/types.go"})

	// 바이너리 의존성
	checker2.AddRule("daemon/cilium-agent", []string{
		"daemon/cmd/daemon.go",
		"daemon/cmd/endpoint.go",
		"pkg/endpoint/endpoint.go",
		"pkg/policy/policy.go",
		"api/v1/models/endpoint.go",
		"api/v1/flow/flow.pb.go",
		"pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go",
	})

	fmt.Println("  코드 생성 재실행 필요 여부:")
	genTargets := []string{
		"api/v1/models/endpoint.go",
		"api/v1/flow/flow.pb.go",
		"pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go",
	}
	for _, target := range genTargets {
		needs, reason := checker2.NeedsRebuild(target)
		status := "SKIP"
		if needs {
			status = "REGEN"
		}
		fmt.Printf("    %-55s -> %-5s  # %s\n", target, status, reason)
	}

	fmt.Println()
	fmt.Println("  바이너리 재빌드 필요 여부:")
	needs, reason := checker2.NeedsRebuild("daemon/cilium-agent")
	status := "SKIP (up-to-date)"
	if needs {
		status = "REBUILD NEEDED"
	}
	fmt.Printf("    %-55s -> %s\n", "daemon/cilium-agent", status)
	fmt.Printf("    Reason: %s\n", reason)

	// 빌드 캐스케이드 시각화
	fmt.Println()
	fmt.Println("[빌드 캐스케이드 분석]")
	fmt.Println()
	fmt.Println("  api/v1/openapi.yaml (수정됨)")
	fmt.Println("    -> api/v1/models/endpoint.go (재생성 필요)")
	fmt.Println("      -> daemon/cilium-agent (재빌드 필요)")
	fmt.Println()
	fmt.Println("  daemon/cmd/daemon.go (수정됨)")
	fmt.Println("    -> daemon/cilium-agent (재빌드 필요)")
	fmt.Println()
	fmt.Println("  bpf/include/bpf/helpers.h (수정됨)")
	fmt.Println("    -> bpf/bpf_lxc.o (재컴파일 필요)")
	fmt.Println("    -> bpf/bpf_host.o (재컴파일 필요)")
	fmt.Println("    -> bpf/bpf_overlay.o (재컴파일 필요)")
	fmt.Println()
}

// =============================================================================
// 보너스: 전체 코드 생성 파이프라인 요약
// =============================================================================

func demoPipelineSummary() {
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println("  보너스: CILIUM 전체 코드 생성 파이프라인 요약")
	fmt.Println("=" + strings.Repeat("=", 79))
	fmt.Println()

	type PipelineStep struct {
		Source     string
		Tool       string
		Target     string
		MakeTarget string
	}

	steps := []PipelineStep{
		{"api/v1/flow/flow.proto", "protoc + protoc-gen-go", "api/v1/flow/flow.pb.go", "generate-hubble-api"},
		{"api/v1/observer/observer.proto", "protoc + protoc-gen-go-grpc", "api/v1/observer/observer_grpc.pb.go", "generate-hubble-api"},
		{"api/v1/flow/flow.proto", "protoc + protoc-gen-go-json", "api/v1/flow/flow.pb.json.go", "generate-hubble-api"},
		{"api/v1/openapi.yaml", "go-swagger generate server", "api/v1/server/", "generate-api"},
		{"api/v1/openapi.yaml", "go-swagger generate client", "api/v1/client/", "generate-api"},
		{"api/v1/openapi.yaml", "go-swagger generate models", "api/v1/models/", "generate-api"},
		{"api/v1/health/openapi.yaml", "go-swagger", "api/v1/health/{server,client}/", "generate-health-api"},
		{"api/v1/operator/openapi.yaml", "go-swagger", "api/v1/operator/{server,client}/", "generate-operator-api"},
		{"pkg/k8s/apis/.../*.go", "deepcopy-gen", "zz_generated.deepcopy.go", "generate-k8s-api"},
		{"pkg/k8s/apis/.../*.go", "deepequal-gen", "zz_generated.deepequal.go", "generate-k8s-api"},
		{"pkg/k8s/apis/.../*.go", "client-gen", "pkg/k8s/client/clientset/", "generate-k8s-api"},
		{"pkg/k8s/apis/.../*.go", "informer-gen", "pkg/k8s/client/informers/", "generate-k8s-api"},
		{"pkg/k8s/apis/.../*.go", "lister-gen", "pkg/k8s/client/listers/", "generate-k8s-api"},
		{"pkg/k8s/apis/cilium.io/v2/*.go", "controller-gen", "client/crds/v2/*.yaml", "manifests"},
		{"pkg/k8s/apis/cilium.io/v2alpha1/*.go", "controller-gen", "client/crds/v2alpha1/*.yaml", "manifests"},
		{"bpf/*.o", "dpgen", "pkg/datapath/config/...", "generate-bpf"},
		{"bpf/*.o", "bpf2go", "pkg/datapath/bpf/...", "generate-bpf"},
	}

	fmt.Printf("  %-40s  %-30s  %-40s  %s\n", "SOURCE", "TOOL", "TARGET", "MAKE TARGET")
	fmt.Printf("  %-40s  %-30s  %-40s  %s\n",
		strings.Repeat("-", 40), strings.Repeat("-", 30), strings.Repeat("-", 40), strings.Repeat("-", 20))

	for _, s := range steps {
		fmt.Printf("  %-40s  %-30s  %-40s  %s\n", s.Source, s.Tool, s.Target, s.MakeTarget)
	}

	fmt.Println()
	fmt.Printf("  합계: %d 코드 생성 단계\n", len(steps))
	fmt.Println()

	fmt.Println("  실행 순서 (make generate-apis && make generate-k8s-api && make manifests && make generate-bpf):")
	fmt.Println("  1. protoc: .proto -> .pb.go, .pb.json.go, _grpc.pb.go")
	fmt.Println("  2. go-swagger: openapi.yaml -> server/, client/, models/")
	fmt.Println("  3. deepcopy-gen: Go types -> zz_generated.deepcopy.go")
	fmt.Println("  4. deepequal-gen: Go types -> zz_generated.deepequal.go")
	fmt.Println("  5. client-gen: Go types -> typed K8s clients")
	fmt.Println("  6. informer-gen: Go types -> informers")
	fmt.Println("  7. lister-gen: Go types -> listers")
	fmt.Println("  8. controller-gen: kubebuilder markers -> CRD YAML")
	fmt.Println("  9. dpgen + bpf2go: BPF objects -> Go code")
	fmt.Println()
}

// =============================================================================
// Main
// =============================================================================

func main() {
	fmt.Println()
	fmt.Println("  Cilium 빌드 시스템 및 코드 생성 PoC")
	fmt.Println("  ====================================")
	fmt.Println()
	fmt.Println("  이 프로그램은 Cilium 프로젝트의 빌드 시스템과")
	fmt.Println("  자동 코드 생성 파이프라인의 핵심 메커니즘을 시뮬레이션합니다.")
	fmt.Println()

	// 구분선
	sep := func() {
		fmt.Println()
		fmt.Println(strings.Repeat("*", 80))
		fmt.Println()
	}

	// 1. Protobuf 코드 생성
	demoProtobufCodegen()
	sep()

	// 2. DeepCopy 코드 생성
	demoDeepCopyCodegen()
	sep()

	// 3. CRD YAML 생성
	demoCRDCodegen()
	sep()

	// 4. Makefile 빌드 의존성 그래프
	demoBuildGraph()
	sep()

	// 5. 증분 빌드 감지
	demoIncrementalBuild()
	sep()

	// 보너스: 전체 파이프라인 요약
	demoPipelineSummary()

	fmt.Println("PoC 실행 완료.")
	os.Exit(0)
}
